"use client";
import { useState, useRef } from "react";
import Link from "next/link";
import { ArrowUpRight, X } from "lucide-react";
import { Sheet, SheetContent, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { localize, localizeHref, type Locale } from "@/lib/i18n";
import type { Wine } from "@/lib/wines/service";
import type { Category } from "@/lib/categories/service";
import type { Localized } from "@/db/schema";
export type { Wine };

type UiStrings = Record<string, Localized>;

function WineCard({wine,onOpen,index,labelFor,locale,t}:{wine:Wine;onOpen:(w:Wine)=>void;index:number;labelFor:(id:string)=>string;locale:Locale;t:UiStrings}) {
  const name=localize(wine.name,locale);
  const content = <><div className="bottle-stage"><span className="bottle-category">{labelFor(wine.category)}</span><ArrowUpRight className="wine-arrow" size={20} strokeWidth={1.3}/><img src={wine.image} alt={name+" bottle"} loading="lazy" width="400" height="650"/><span className="wine-discover">{localize(t["wine.discoverWine"],locale)}</span></div><div className="wine-card-title"><h3>{name}</h3><span>{String(index+1).padStart(2,"0")}</span></div><p className="wine-card-note">{wine.grapes?localize(wine.grapes,locale):labelFor(wine.category)}{wine.style?" / "+localize(wine.style,locale):""}</p></>;
  const className = "wine-card tone-" + wine.category;
  const label = "Discover " + name;
  return <button className={className} onClick={() => onOpen(wine)} aria-label={label}>{content}</button>;
}
function WineDetails({wine,onClose,returnFocus,labelFor,locale,t}:{wine:Wine|null;onClose:()=>void;returnFocus:HTMLElement|null;labelFor:(id:string)=>string;locale:Locale;t:UiStrings}){
  const name=wine?localize(wine.name,locale):"";
  return <Sheet open={!!wine} onOpenChange={open=>{if(!open)onClose()}}><SheetContent className="wine-panel" showCloseButton={false} onCloseAutoFocus={event=>{event.preventDefault();returnFocus?.focus()}}>{wine&&<><div className="wine-panel-top"><span className="eyebrow">{localize(t["wine.theBadagoniCollection"],locale)}</span><SheetClose aria-label="Close wine details" className="panel-close"><X size={23} strokeWidth={1.3}/></SheetClose></div><div className={"wine-detail-image tone-"+wine.category}><img src={wine.image} alt={name+" bottle"} width="500" height="700"/></div><div className="wine-detail-copy"><p className="eyebrow">{labelFor(wine.category)}{wine.style?" · "+localize(wine.style,locale):""}</p><SheetTitle className="wine-detail-title">{name}</SheetTitle><SheetDescription className="wine-detail-description">{wine.description?localize(wine.description,locale):localize(t["wine.fallbackDescription"],locale)}</SheetDescription><dl className="wine-specs"><div><dt>{localize(t["wine.origin"],locale)}</dt><dd>{localize(t["wine.georgia"],locale)}</dd></div>{wine.grapes&&<div><dt>{localize(t["wine.grapeVariety"],locale)}</dt><dd>{localize(wine.grapes,locale)}</dd></div>}{wine.alcohol&&<div><dt>{localize(t["wine.alcohol"],locale)}</dt><dd>{wine.alcohol}</dd></div>}{wine.specs?.map((spec,i)=><div key={i}><dt>{localize(spec.label,locale)}</dt><dd>{localize(spec.value,locale)}</dd></div>)}</dl><div className="wine-panel-actions"><Link className="text-link" href={localizeHref("/wines/"+wine.slug,locale)}>{localize(t["wine.viewFullWinePage"],locale)} <ArrowUpRight size={18}/></Link><a className="text-link" href={"mailto:office@badagoni.ge?subject="+encodeURIComponent("Enquiry: "+name)}>{localize(t["wine.enquireAboutThisWine"],locale)} <ArrowUpRight size={18}/></a></div></div></>}</SheetContent></Sheet>;
}
export function FeaturedWines({wines,categories,locale,t}:{wines:Wine[];categories:Category[];locale:Locale;t:UiStrings}){const labelFor=(id:string)=>{const c=categories.find(c=>c.id===id);return c?localize(c.label,locale):id};const [selected,setSelected]=useState<Wine|null>(null);const returnFocus=useRef<HTMLElement|null>(null);const openWine=(wine:Wine)=>{returnFocus.current=document.activeElement as HTMLElement;setSelected(wine)};const featured=["saperavi-reserve","alaverdi-tradition-white-qvevri-wine","badagoni-brut"].map(slug=>wines.find(w=>w.slug===slug)).filter((w):w is Wine=>!!w);return <><div className="wine-grid featured-grid">{featured.map((wine,i)=><WineCard key={wine.slug} wine={wine} index={i} onOpen={openWine} labelFor={labelFor} locale={locale} t={t}/>)}</div><WineDetails wine={selected} onClose={()=>setSelected(null)} returnFocus={returnFocus.current} labelFor={labelFor} locale={locale} t={t}/></>}
export function WineCollection({wines,categories,locale,t}:{wines:Wine[];categories:Category[];locale:Locale;t:UiStrings}){const labelFor=(id:string)=>{const c=categories.find(c=>c.id===id);return c?localize(c.label,locale):id};const filters=[{id:"all",name:localize(t["wine.allFilter"],locale)},...categories.map(c=>({id:c.id,name:localize(c.label,locale)}))];const [selected,setSelected]=useState<Wine|null>(null);const returnFocus=useRef<HTMLElement|null>(null);const openWine=(wine:Wine)=>{returnFocus.current=document.activeElement as HTMLElement;setSelected(wine)};const [filter,setFilter]=useState("all");return <><Tabs value={filter} onValueChange={setFilter} className="collection-tabs"><div className="filter-row"><TabsList className="wine-filters" variant="line" aria-label="Wine categories">{filters.map(f=><TabsTrigger className="wine-filter" key={f.id} value={f.id}>{f.name}</TabsTrigger>)}</TabsList><span className="wine-count" aria-live="polite">{(filter==="all"?wines:wines.filter(w=>w.categories.includes(filter))).length} {localize(t["wine.expressionsSuffix"],locale)}</span></div>{filters.map(f=><TabsContent key={f.id} value={f.id}><div className="wine-grid catalog-grid">{(f.id==="all"?wines:wines.filter(w=>w.categories.includes(f.id))).map((wine,i)=><WineCard key={wine.slug} wine={wine} index={i} onOpen={openWine} labelFor={labelFor} locale={locale} t={t}/>)}</div></TabsContent>)}</Tabs><WineDetails wine={selected} onClose={()=>setSelected(null)} returnFocus={returnFocus.current} labelFor={labelFor} locale={locale} t={t}/></>}
