"use client";
import { useState, useRef } from "react";
import Link from "next/link";
import { ArrowUpRight, X } from "lucide-react";
import { Sheet, SheetContent, SheetTitle, SheetDescription, SheetClose } from "@/components/ui/sheet";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import type { Wine } from "@/lib/wines/service";
import type { Category } from "@/lib/categories/service";
export type { Wine };

function WineCard({wine,onOpen,index,labelFor}:{wine:Wine;onOpen:(w:Wine)=>void;index:number;labelFor:(id:string)=>string}) {
  const content = <><div className="bottle-stage"><span className="bottle-category">{labelFor(wine.category)}</span><ArrowUpRight className="wine-arrow" size={20} strokeWidth={1.3}/><img src={wine.image} alt={wine.name.en+" bottle"} loading="lazy" width="400" height="650"/><span className="wine-discover">Discover wine</span></div><div className="wine-card-title"><h3>{wine.name.en}</h3><span>{String(index+1).padStart(2,"0")}</span></div><p className="wine-card-note">{wine.grapes?.en || labelFor(wine.category)}{wine.style?" / "+wine.style.en:""}</p></>;
  const className = "wine-card tone-" + wine.category;
  const label = "Discover " + wine.name.en;
  return <button className={className} onClick={() => onOpen(wine)} aria-label={label}>{content}</button>;
}
function WineDetails({wine,onClose,returnFocus,labelFor}:{wine:Wine|null;onClose:()=>void;returnFocus:HTMLElement|null;labelFor:(id:string)=>string}){return <Sheet open={!!wine} onOpenChange={open=>{if(!open)onClose()}}><SheetContent className="wine-panel" showCloseButton={false} onCloseAutoFocus={event=>{event.preventDefault();returnFocus?.focus()}}>{wine&&<><div className="wine-panel-top"><span className="eyebrow">The Badagoni collection</span><SheetClose aria-label="Close wine details" className="panel-close"><X size={23} strokeWidth={1.3}/></SheetClose></div><div className={"wine-detail-image tone-"+wine.category}><img src={wine.image} alt={wine.name.en+" bottle"} width="500" height="700"/></div><div className="wine-detail-copy"><p className="eyebrow">{labelFor(wine.category)}{wine.style?" · "+wine.style.en:""}</p><SheetTitle className="wine-detail-title">{wine.name.en}</SheetTitle><SheetDescription className="wine-detail-description">{wine.description?.en||"Discover this expression from the Badagoni collection. Contact our team for current vintages and further information."}</SheetDescription><dl className="wine-specs"><div><dt>Origin</dt><dd>Georgia</dd></div>{wine.grapes&&<div><dt>Grape variety</dt><dd>{wine.grapes.en}</dd></div>}{wine.alcohol&&<div><dt>Alcohol</dt><dd>{wine.alcohol}</dd></div>}</dl><div className="wine-panel-actions"><Link className="text-link" href={"/wines/"+wine.slug}>View full wine page <ArrowUpRight size={18}/></Link><a className="text-link" href={"mailto:office@badagoni.ge?subject="+encodeURIComponent("Enquiry: "+wine.name.en)}>Enquire about this wine <ArrowUpRight size={18}/></a></div></div></>}</SheetContent></Sheet>}
export function FeaturedWines({wines,categories}:{wines:Wine[];categories:Category[]}){const labelFor=(id:string)=>categories.find(c=>c.id===id)?.label.en??id;const [selected,setSelected]=useState<Wine|null>(null);const returnFocus=useRef<HTMLElement|null>(null);const openWine=(wine:Wine)=>{returnFocus.current=document.activeElement as HTMLElement;setSelected(wine)};const featured=["saperavi-reserve","alaverdi-tradition-white-qvevri-wine","badagoni-brut"].map(slug=>wines.find(w=>w.slug===slug)).filter((w):w is Wine=>!!w);return <><div className="wine-grid featured-grid">{featured.map((wine,i)=><WineCard key={wine.slug} wine={wine} index={i} onOpen={openWine} labelFor={labelFor}/>)}</div><WineDetails wine={selected} onClose={()=>setSelected(null)} returnFocus={returnFocus.current} labelFor={labelFor}/></>}
export function WineCollection({wines,categories}:{wines:Wine[];categories:Category[]}){const labelFor=(id:string)=>categories.find(c=>c.id===id)?.label.en??id;const filters=[{id:"all",name:"All"},...categories.map(c=>({id:c.id,name:c.label.en}))];const [selected,setSelected]=useState<Wine|null>(null);const returnFocus=useRef<HTMLElement|null>(null);const openWine=(wine:Wine)=>{returnFocus.current=document.activeElement as HTMLElement;setSelected(wine)};const [filter,setFilter]=useState("all");return <><Tabs value={filter} onValueChange={setFilter} className="collection-tabs"><div className="filter-row"><TabsList className="wine-filters" variant="line" aria-label="Wine categories">{filters.map(f=><TabsTrigger className="wine-filter" key={f.id} value={f.id}>{f.name}</TabsTrigger>)}</TabsList><span className="wine-count" aria-live="polite">{(filter==="all"?wines:wines.filter(w=>w.categories.includes(filter))).length} expressions</span></div>{filters.map(f=><TabsContent key={f.id} value={f.id}><div className="wine-grid catalog-grid">{(f.id==="all"?wines:wines.filter(w=>w.categories.includes(f.id))).map((wine,i)=><WineCard key={wine.slug} wine={wine} index={i} onOpen={openWine} labelFor={labelFor}/>)}</div></TabsContent>)}</Tabs><WineDetails wine={selected} onClose={()=>setSelected(null)} returnFocus={returnFocus.current} labelFor={labelFor}/></>}
